force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Item__c/Supplier_Item__c.object-meta.xml
<CustomObject>
    <label>Supplier Item</label>
    <nameField>
        <label>Supplier Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Supplier_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Item__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Supplier account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Items</relationshipLabel>
    <relationshipName>Supplier_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/treeController.cls
public class treeController {
     
    @AuraEnabled
    public static List<item> getAccountTree(){
         
        List<item> items = new List<item>();
        List<Account> acctList = new List<Account>();
        //get list of accounts and respective supplier items
        acctList = [SELECT Id, Name, (SELECT Id, Name,Item__c From Supplier_Materials__r) From Account LIMIT 10];
        for(Account acc: acctList){
             
            List<item> conitems = new List<item>();
            
            //get supplier items of current account record
            for(Supplier_Item__c c: acc.Supplier_Materials__r){
                List<item> supitems = new List<item>();
                List<Item__c> temp = new List<Item__c>();
                temp = [SELECT Id, Name From Item__c where Id=:c.Item__c]; 
                for (Item__c i : temp)
                {
                    // add items__c
                    item supitem = new item(i.Name, String.valueOf(i.Id), false, null);
                    supitems.add(supitem);
                }
                //add supplier items
                item conitem = new item(c.Name, String.valueOf(c.Id), false, supitems);
                conitems.add(conitem);
            }
            //add account items
            item accitem = new item(acc.Name, String.valueOf(acc.Id), false, conitems);
            items.add(accitem);
        }
        return items;
    }

    //Item Wrapper Class
    public class item{
        @AuraEnabled
        public String label {get; set;}
        @AuraEnabled
        public String name {get; set;}
        @AuraEnabled
        public Boolean expanded {get; set;}
        @AuraEnabled
        public List<item> items {get; set;}
         
        public item(String label, String name, Boolean expanded, List<item> items){
            this.label = label;
            this.name = name;
            this.expanded = expanded;
            this.items = items;
        }
    }
}