force-app/main/default/objects/Bill_of_Materials__c/Bill_of_Materials__c.object-meta.xml
<CustomObject>
    <label>Bill of Materials</label>
    <nameField>
        <displayFormat>BoM-{00000}</displayFormat>
        <label>Bill of Materials Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills of Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill_of_Materials__c/fields/Effectivity_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Effectivity_End_Date__c</fullName>
    <label>Effectivity End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bill_of_Materials__c/fields/Effectivity_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Effectivity_Start_Date__c</fullName>
    <label>Effectivity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bill_of_Materials__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Bills of Materials</relationshipLabel>
    <relationshipName>Bills_of_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finished Good</fullName>
            </value>
            <value>
                <fullName>Assembly</fullName>
            </value>
            <value>
                <fullName>Purchased Good</fullName>
            </value>
            <value>
                <fullName>Raw Material</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Primary_BoM__c.field-meta.xml
<CustomField>
    <fullName>Primary_BoM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary BoM</label>
    <referenceTo>Bill_of_Materials__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Item__c/Supplier_Item__c.object-meta.xml
<CustomObject>
    <label>Supplier Item</label>
    <nameField>
        <label>Supplier Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Supplier_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Item__c/fields/Spend__c.field-meta.xml
<CustomField>
    <fullName>Spend__c</fullName>
    <label>Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Item__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Supplier account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Items</relationshipLabel>
    <relationshipName>Supplier_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/treeAuraController.cls
public with sharing class treeAuraController {
    @AuraEnabled
    public static List<wrapperitem> getAccountTree()
    {
    System.debug('in getAccount Tree ');
    List<wrapperitem> items = new List<wrapperitem>();
    List<Account> acctList = new List<Account>();
        //get list of accounts and respective contacts
        List<Supplier_Item__c> suppliers = new List<Supplier_Item__c>(); 
        suppliers = [SELECT Id, Name, Spend__c, Supplier__r.Name, Supplier__c, Item__c, Item__r.Name FROM Supplier_Item__c]; 

        //acctList = [SELECT Id, Name, (SELECT Id, Name From Contacts) From Account LIMIT 10];
            for(Supplier_Item__c acc: suppliers){
            
            List<wrapperitem> conitems = new List<wrapperitem>();
            List<Bill_of_Materials__c> bom = new List<Bill_of_Materials__c>();
            bom = [SELECT Id, Name, Item__c, Item__r.Name, Effectivity_Start_Date__c, Effectivity_End_Date__c From Bill_of_Materials__c WHERE Item__c =:acc.Item__c];
            System.debug('supplier and bom ' + acc.Name + ' ' + bom); 
        

            for(Bill_of_Materials__c b : bom)
            {

                System.debug('bom ' + b.Name);   
                wrapperitem conitem = new wrapperitem(b.Item__r.Name, String.valueOf(b.Item__c),false, null); 
                conitems.add(conitem);
            }

            System.debug('con Items ' + conitems);      
            wrapperitem supplieritem = new wrapperitem(acc.Name, String.valueOf(acc.Id),false, null);
            items.add(supplieritem);
        }

        System.debug(' Final Items ' + items);      
        return items;
    }
    
       //Item Wrapper Class
       public class wrapperitem{
       @AuraEnabled
       public String itemName {get; set;}
       @AuraEnabled
       public String itemId {get; set;}
       @AuraEnabled
       public Boolean expanded {get; set;}
       @AuraEnabled
       public List<wrapperitem> items {get; set;}

       
       public wrapperitem(String itemName, String itemId,Boolean expanded,List<wrapperitem> items){
           this.itemName = itemName;
           this.itemId = itemId;
           this.expanded = expanded;
           this.items = items;
       }
   }
}

        //List<Bill_of_Materials__c> bom = New List<Bill_of_Materials__c>();
        //bom = [SELECT Id, Name, Item__c, Item__r.Name, Effectivity_Start_Date__c, Effectivity_End_Date__c From Bill_of_Materials__c WHERE Item__c =:acc.Item__c LIMIT 10];

    /* String itemName; 
    String itemType;
    String itemId; 

    itemId = bom[0].Item__c; 
    itemId = acc.Item__c; 
    
    Item__c item = [SELECT Id, Name, Item_Type__c, Primary_BoM__c From Item__c Where Id =:itemId];

    List<wrapperitem> conitems = new List<wrapperitem>();
    
        wrapperitem conitem = new item(acc.Name, bom.Name, false, null);
        conitems.add(conitem);
    */
    
    
            
        //add account items


                /*List<wrapperitem> primarybom = new List<wrapperitem>();
                List<Item__c> itm = new List<Item__c>();
                itm = [SELECT Id, Name, Primary_BoM__c From Item__c  WHERE Primary_BoM__c =:b.Id];
                System.debug('item ' + itm); 

                for(Item__c i: itm)
                {
                    System.debug('itm ' + i.Name);   
                    wrapperitem i_item = new wrapperitem(i.Name, String.valueOf(i.Id),false, null); 
                    primarybom.add(i_item);
                }*/