force-app/main/default/objects/BoM_Line__c/BoM_Line__c.object-meta.xml
<CustomObject>
    <label>BoM Line</label>
    <nameField>
        <displayFormat>BoMLine-{000000}</displayFormat>
        <label>BoM Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BoM Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BoM_Line__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>BoM Lines</relationshipLabel>
    <relationshipName>BoM_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Item__c/Supplier_Item__c.object-meta.xml
<CustomObject>
    <label>Supplier Item</label>
    <nameField>
        <label>Supplier Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Supplier_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Item__c/fields/Spend__c.field-meta.xml
<CustomField>
    <fullName>Spend__c</fullName>
    <label>Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Item__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Supplier account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Items</relationshipLabel>
    <relationshipName>Supplier_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SampleAuraController.cls
public with sharing class SampleAuraController {
    @AuraEnabled
    public static List <Account> getAccountList() {
        System.debug('## inside get Account list'); 

        List<Account> accList = new List<Account>();
        /*accList = [SELECT Id, Name, NumberOfEmployees, Phone,
                   (SELECT FirstName, LastName, Email FROM Contacts)
                   FROM Account LIMIT 10];*/

        accList= [SELECT Id, Name, (SELECT Id, Name, Spend__c, Supplier__r.Name, Supplier__c, Item__c, Item__r.Name from Supplier_Materials__r) From Account];
        System.debug('## account list ' + accList); 
        return accList;
    }

    @AuraEnabled
    public static List <Item__c> getItemsList() {

        System.debug('## inside get Items list'); 
        List<Item__c> itmList = new List<Item__c> (); 
        itmList = [SELECT Id, Name, (SELECT Id, Name,Quantity__c,Spend__c from Supplier_Items__r) From Item__c  LIMIT 10];
        System.debug('## item supplier list ' + itmList); 
        return itmList;
    }

    @AuraEnabled
    public static List <Item__c> getBOM() {

        System.debug('## inside get BOM list'); 
        List<Item__c> itmList = new List<Item__c> (); 
        itmList = [SELECT Id, Name, (SELECT Id, Name, Quantity__c from BoM_Lines__r) From Item__c  LIMIT 10];
        System.debug('## item Bom list ' + itmList); 
        return itmList;
    }
}